create table addresses
(id bigint generated by default as identity,
 line_no_one varchar(3000) not null,
 line_no_two varchar(3000) not null,
 city varchar(500) not null,
 state varchar(500) not null,
 pin_code varchar(100) not null,
 country varchar(100) not null,
 is_default boolean,
 user_id bigint,
 primary key (id),
 CONSTRAINT fk_user_addresses FOREIGN KEY(user_id) references users(id))
