create table orders
(id bigint generated by default as identity,
 recipient_name varchar(64) not null,
 book_id bigint not null,
 address_id bigint not null,
 quantity int not null default 1,
 created_at timestamp not null DEFAULT CURRENT_TIMESTAMP,
 primary key (id),
 CONSTRAINT fk_order_book FOREIGN KEY(book_id) references books(id),
 CONSTRAINT fk_order_address FOREIGN KEY(address_id) references addresses(id));
